apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-code-with-quarkus-ke6y
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/msawood-tenant/my-app-custom-pipeline/devfile-sample-code-with-quarkus-ke6y@sha256:3fea25a1896501ed1abeb2729b9caa383adf79de45836c7cdb6e33bb52e82641
        name: my-java-quarkus
        resources: {}
status: {}
